#!/usr/bin/bash

TYPE=${1:-rootfs}
VENDOR=${2:-"<com.example.vendor.Product>"}
ARCH=${3:-"x86_64"}
VERSION=${4:-$(date +%Y%m%d%H%M%S)}
EXTRA_RELEASE=${5:-${EXTRA_RELEASE}}

if [[ -n $@ ]];
then
echo ${TYPE}:${VENDOR}:${ARCH}:${VERSION}${EXTRA_RELEASE}
else
echo "Usage: $0 TYPE NAME VENDOR [ARCH] [VERSION] [EXTRA_RELEASE]"
fi
